services:
  adguard:
    image: adguard/adguardhome
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    container_name: adguard
    networks:
    - default
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 6443:6443/tcp
    - 86:80/tcp
    - 3020:3000/tcp
    volumes:
    - $CORE_DATA/adguard/conf:/opt/adguardhome/conf
    - $CORE_DATA/adguard/work:/opt/adguardhome/work
    mem_limit: 512m
    cpus: 0.5

volumes:
  config:
    driver: local
  work:
    driver: local
