services:
  element_web:
    image: vectorim/element-web:latest
    container_name: element_web
    restart: unless-stopped
    networks:
      - professional
      - proxy

    volumes:
      - ${PRO_DATA}/matrix/element/config.json:/app/config.json:ro

    labels:
      - "traefik.enable=true"

      ## Router ###
      - "traefik.http.routers.element-rtr.entrypoints=websecure"
      - "traefik.http.routers.element-rtr.rule=Host(`chat.${DOMAINNAME_1}`)"
      - "traefik.http.routers.element-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.element-rtr.service=element-svc"

      ## Service ###
      - "traefik.http.services.element-svc.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"